# Generated by Django 3.1.2 on 2020-10-16 01:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.SmallIntegerField(choices=[(0, 'chinese'), (1, 'culture'), (2, 'adult')], verbose_name='course type')),
                ('course_name', models.CharField(max_length=250, verbose_name='course name')),
                ('course_desp', models.TextField(blank=True, max_length=250, verbose_name='course description')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='modified data')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
    ]
