# Generated by Django 3.1.2 on 2020-11-15 21:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=135, verbose_name='student name')),
                ('address', models.CharField(max_length=135, verbose_name='address')),
                ('phone', models.CharField(max_length=135, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=135, verbose_name='email')),
                ('registered_class', models.CharField(blank=True, max_length=135, verbose_name='registered class')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='created date')),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='modified data')),
                ('contact_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='contact_name')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
    ]
