# Generated by Django 3.1.2 on 2020-11-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentext',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
    ]
